spring.application.name=lapstore

server.port=8080

spring.jpa.database=POSTGRESQL
spring.datasource.platform=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/lapstore
spring.datasource.username=postgres
spring.datasource.password=123484

spring.jpa.hibernate.ddl-auto=validate

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/changeLogMaster.xml

logging.level.liquibase=DEBUG

spring.jpa.show-sql=false
